---
- include_vars: servers.yml
  tags: debug
- apt: >
    deb=https://github.com/sysown/proxysql/releases/download/v1.2.0k/proxysql_1.2.0-ubuntu14_amd64.deb

- file: >
    path="/etc/proxysql.cnf"
    state=absent
- template: >
    src=proxysql.conf.tmpl
    dest=/etc/proxysql.cnf

- service: >
    name=proxysql
    state=running
#put sleep here!!!
- pause: seconds=5 
- name: workaround for bug https://github.com/sysown/proxysql/issues/617 
  command: >
    mysql 
    --user={{ proxysql.admin_user }}
    --password={{ proxysql.admin_passwd }}
    --host={{ proxysql.admin_host }}  
    --port={{ proxysql.admin_port }}  
    --execute "LOAD MYSQL USERS FROM CONFIG;LOAD MYSQL SERVERS FROM CONFIG;LOAD MYSQL QUERY RULES FROM CONFIG;LOAD MYSQL VARIABLES FROM CONFIG;LOAD MYSQL USERS TO RUNTIME;LOAD MYSQL SERVERS TO RUNTIME; LOAD MYSQL QUERY RULES TO RUNTIME; LOAD MYSQL VARIABLES TO RUNTIME; "

- name: workaround for bug https://github.com/sysown/proxysql/issues/617 
  command: >
    mysql 
    --user={{ proxysql.admin_user }}
    --password={{ proxysql.admin_passwd }}
    --host={{ proxysql.admin_host }}  
    --port={{ proxysql.admin_port }}  
    --execute "set admin-mysql_ifaces='0.0.0.0:6032;/tmp/proxysql_admin.sock'; LOAD ADMIN VARIABLES TO RUNTIME;"

#create app user on the mysql master
- mysql_user: >
    login_host={{ mysql_servers.damp_server1 }}
    login_user={{ mysql.login_user }} 
    login_password={{ mysql.login_passwd }}
    name={{ proxysql.app_user }}
    password={{ proxysql.app_passwd }}  
    priv={{ proxysql.app_priv }}
    host={{ proxysql.app_host }}
    state=present

#create monitor user on the mysql master
- mysql_user: >
    login_host={{ mysql_servers.damp_server1 }}
    login_user={{ mysql.login_user }} 
    login_password={{ mysql.login_passwd }}
    name={{ proxysql.monitor_user }}
    password={{ proxysql.monitor_passwd }}  
    priv={{ proxysql.monitor_priv }}
    host={{ proxysql.monitor_host }}
    state=present
  tags: debug


- name: add servers to proxysql and load them
  command: >
    mysql 
    --user={{ proxysql.admin_user }}
    --password={{ proxysql.admin_passwd }}
    --host={{ proxysql.admin_host }}  
    --port={{ proxysql.admin_port }}  
    --execute "
    REPLACE INTO mysql_servers 
        ( hostgroup_id, hostname, port, max_replication_lag) 
    VALUES 
        (1, '{{ item.value }}', 3306, 20);"
  with_dict: "{{ mysql_servers }}"
  notify:   
    - load proxysql changes to runtime
    - save proxysql changes to disk
  tags: debug

#create app user on the master
- name: workaround for bug https://github.com/sysown/proxysql/issues/617 
  command: >
    mysql 
    --user={{ proxysql.admin_user }}
    --password={{ proxysql.admin_passwd }}
    --host={{ proxysql.admin_host }}  
    --port={{ proxysql.admin_port }}  
    --execute "
    REPLACE INTO 
        mysql_users (username, password, active, default_hostgroup, max_connections) 
    VALUES 
        ('{{ proxysql.app_user }}', '{{ proxysql.app_passwd }}', 1, 0, {{ proxysql.app_max_conn }});"
  notify:
    - load proxysql changes to runtime
    - save proxysql changes to disk

- debug: var=mysql_servers
  tags: debug
