---
- include_vars: servers.yml
- apt: >
    deb=https://github.com/sysown/proxysql/releases/download/v1.2.2/proxysql_1.2.2-ubuntu14_amd64.deb

- file: >
    path="/etc/proxysql.cnf"
    state=absent
- template: >
    src=proxysql.conf.tmpl
    dest=/etc/proxysql.cnf

- service: >
    name=proxysql
    state=running

- wait_for: host={{ proxysql.admin_host }} port={{ proxysql.admin_port }}  delay=3 state=started 

#create app user on the mysql masters
- mysql_user: >
    login_host={{ item.1 }}
    login_user={{ mysql.login_user }} 
    login_password={{ mysql.login_passwd }}
    name={{ proxysql.app_user }}
    password={{ proxysql.app_passwd }}  
    priv={{ proxysql.app_priv }}
    host={{ proxysql.app_host }}
    state=present
  with_subelements:
    - "{{ mysql_servers }}"
    - master

#create monitor user on the mysql masters
- mysql_user: >
    login_host={{ item.1 }}
    login_user={{ mysql.login_user }} 
    login_password={{ mysql.login_passwd }}
    name={{ proxysql.monitor_user }}
    password={{ proxysql.monitor_passwd }}  
    priv={{ proxysql.monitor_priv }}
    host={{ proxysql.monitor_host }}
    state=present
  with_subelements:
    - "{{ mysql_servers }}"
    - master

- name: proxysql | config | add users
  proxysql_mysql_users:
    login_host:         "{{ proxysql.admin_host }}"
    login_port:         "{{ proxysql.admin_port }}"
    login_user:         "{{ proxysql.admin_user }}"
    login_password:     "{{ proxysql.admin_passwd }}"
    username:           "{{ proxysql.app_user }}"
    password:           "{{ proxysql.app_passwd }}"
    max_connections:    "{{ proxysql.app_max_conn }}"
    default_hostgroup:  "{{ proxysql.app_default_hostgroup }}"
    state: present
        

- name: proxysql | config | add replication hostgroups
  proxysql_replication_hostgroups:
    login_host:         "{{ proxysql.admin_host }}"
    login_port:         "{{ proxysql.admin_port }}"
    login_user:         "{{ proxysql.admin_user }}"
    login_password:     "{{ proxysql.admin_passwd }}"
    writer_hostgroup:   "{{ item.0.hostgroup }}"
    reader_hostgroup:   "{{ item.0.hostgroup | int + 1  }}"
    comment:            "{{ item.0.clustername }}"
    load_to_runtime:    True
    state: present
  with_subelements:
    - "{{ mysql_servers }}"
    - master

- name: proxysql | config | add server
  proxysql_backend_servers:
    login_host:     "{{ proxysql.admin_host }}"
    login_port:     "{{ proxysql.admin_port }}"
    login_user:     "{{ proxysql.admin_user }}"
    login_password: "{{ proxysql.admin_passwd }}"
    hostname:       "{{ item.1 }}"
    hostgroup_id:   "{{ item.0.hostgroup }}"     
    port:           "3306"
    load_to_runtime: True
    state:           present
  with_subelements:
    - "{{ mysql_servers }}"
    - servers

