---
dependencies: []

galaxy_info:
  author: Your Name
  description: Common role for DAMP stack
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8 